# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correlation', '0002_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6)),
            ],
        ),
    ]
